apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: regapp
    app.kubernetes.io/name: regapp

spec:
  selector:
    app: regapp

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional: only for NodePort services

  type: LoadBalancer  # Change to NodePort if not using a cloud provider
